name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: List runner info
      run: sw_vers && arch
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.3.0.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Run tests
      run: ./run_tests.sh

  build-release:
    name: Build release
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.3.0.app/Contents/Developer
    - name: Build
      run: ./build_release.sh
